### ISSUE TITLE
v1.0.0 checklist [deprecated]

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#186]
A list of current issues I'm tackling on the `dev` branch for the upcoming `v1.0.0` release (soon, I promise!)

**In progress**
- [x] Implement a `spectral` base for wavelength dependence.
- [ ] Implement a `temporal` base for time dependence via a custom basis provided by the user.
- [x] Implement a `reflected` base for maps in reflected light.
- [x] Optimize the backpropagation in all C++ methods.
- [ ] Add bounds checking on variables. Is this possible in Theano?
- [x] Optimize the methods in `Map()`. Can we write them in such a way to remove the overhead when calling `X` and `flux` repeatedly?
- [x] Can we figure out a way to auto-evaluate methods if the user doesn't provide any Theano variables as input? Perhaps have the user set a flag `theano=False` when instantiating a `Map`?
- [ ] Add the pure limb darkening flux calculation back in.
- [ ] Add wavelength-dependent limb darkening. *EDIT: We may want to only do this for pure limb darkening, since for Ylm maps the problem will no longer be linear in the ylms.*
- [ ] Exposure time integration.

**Methods still to be implemented**
- [ ] `is_physical()`, `max()`, `min()`: Finding the extrema of the map.
- [x] `add_spot()`: Add a gaussian spot to the map

**To do**
- [x] Pop all kwargs & test for unused ones in all methods
- [x] Add a map luminosity term and compute its gradient. This effectively replaces the ability to set the `Y_{0,0}` coefficient.
- [ ] Think about normalization for spectral maps. See #171.
- [ ] Implement the fluence integrals from the `fluence` branch.
- [ ] Add tests to evaluate the stability of the flux and its derivatives near all singular points.
- [ ] Ensure Python 2 compatibility?
- [ ] Large l maps (`lmax` > 40) take many seconds to instantiate! Check this out.
- [ ] Re-think our changes of basis, which are quite ill-conditioned at large `l`. The issue is that at large `l`, the *polynomial* coefficients corresponding to any given spherical harmonic can vary by many, many orders of magnitude, leading to numerical instabilities down the line. There could exist a more stable Green's basis that avoids these issues. The same applies to the `limbdark` integrals, which are unstable for the same reason.

**Completed**
- [x] Think about how to deal with indexing of multi-column maps. *EDIT: For multi-column maps, users must now explicitly specify the column index or provide `:` to set all coefficients simultaneously.*
- [x] Add a `zo` argument to flux for occultor z position.
- [x] Linearize the limb darkening operator for spherical harmonic maps. *EDIT: This was easier than I expected! Limb darkening is now simply a change of basis operation, so it's linear as long as `Y_{0,0}` is fixed at unity.*
- [x] Should the coefficient of the `Y_{0,0}` term default to unity? *EDIT: Yes! The user can no longer set this coefficient.*
- [x] Specify the axis of rotation by an inclination and an obliquity, not a vector in xyz. *EDIT: Both are now options. Internally, `starry` uses the two angles.*
- [x] Implement a linear model for the map coefficients. See #78. *EDIT: This is now how `starry` computes everything internally.*
- [x] Implement a Rossiter-McLaughlin map class. *EDIT: This is currently done by setting `doppler=True` when instantiating a map.

**Comment by rodluger** [comment]
And here is a running list of all the changes in v1.0.0 (in no particular order). This will be incorporated into the CHANGELOG upon release:

- The normalization of limb-darkened spherical harmonic maps has changed. The normalization is such that the total **luminosity** of the map remains unchanged when limb darkening is applied or when the limb darkening coefficients are modified. Note that this could mean that the **flux** at any given viewing angle will be different from the non-limb-darkened version of the map. This is significantly different from the beta version of the code, which normalized it such that the **flux** remained unchanged. That normalization was almost certainly unphysical.
- Added a `Temporal` map class. The columns of the map matrix of a `Temporal` map are the terms in the Taylor expansion of the map as a function of time.
- The change of basis matrices between spherical harmonics and polynomials are now computed recursively, rather than via the horrendous nested sums presented in the paper. The new method is more elegant *and* more stable.
- `starry` can now finally be used directly in C++ as a header-only library, with no Python dependencies. 
- The `boost` dependency is now optional and required only for multi-precision maps.

**Comment by rodluger** [comment]
Deprecated in favor of #207
