### ISSUE TITLE
v1.0.0 todo

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#207]
- [ ] Change the re-direct link on the [docs landing page](https://github.com/rodluger/starry/blob/gh-pages/index.html) to point to the new version
- [ ] Update all links on the [README](https://github.com/rodluger/starry/blob/dev/README.md).
- [ ] Update the Azure pipelines triggers to point to the `master` branch.
- [ ] Update `runBranch` in `build_docs.yml`

**Comment by ericagol** [comment]
Let me know if there are any computations I can help to support this with.

**Comment by rodluger** [comment]
@ericagol Will do! For now it's mostly just a matter of implementing & testing stuff I've already worked out, but I'll ping you if I run into something I need help with.
