### ISSUE TITLE
Checklist for next version

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#262]
- [x] Remove `healpy` dependence (causing errors with OpenMP). Code up our own custom SHT
- [x] Ensure compatibility with all recent versions of `theano` and `theano-pymc`
- [x] Remove differential rotation stuff (deprecated)
- [x] Deprecate the `add_spot` method in favor of the spot algorithm in `starry-process`
- [x] Switch to Github Actions

**Comment by rodluger** [comment]
Doing all this on branch restructure: https://github.com/rodluger/starry/tree/restructure
